name: MacOS
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-14
    strategy:
      matrix:
        qt-ver: [6.5.3]
        include:
          - qt-ver: 6.5.3
            qt-arch-install: macos
            build-arch: arm64
    env:
      target-name: Zentroid
      plantform-des: mac
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ matrix.qt-ver }}
          modules: qtmultimedia
          cache: true

      - name: Build MacOS
        env:
          ENV_QT_PATH: ${{ env.QT_ROOT_DIR }}/..
        run: |
          echo "QT_ROOT_DIR=$QT_ROOT_DIR"
          python3 ci/generate-version.py
          chmod +x ci/mac/build_for_mac.sh
          ci/mac/build_for_mac.sh RelWithDebInfo ${{ matrix.build-arch }}

      - name: Get the version
        shell: bash
        id: get-version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Package
        id: package
        env:
          publish_name: ${{ env.target-name }}-${{ env.plantform-des }}-${{ matrix.build-arch }}-Qt${{ matrix.qt-ver }}-${{ steps.get-version.outputs.version }}
        run: |
          chmod +x ci/mac/publish_for_mac.sh ci/mac/package_for_mac.sh
          ci/mac/publish_for_mac.sh ../build ${{ matrix.build-arch }} || true
          ci/mac/package_for_mac.sh || true
          mv ci/build/Zentroid.app ci/build/${{ env.publish_name }}.app 2>/dev/null || true
          mv ci/build/Zentroid.dmg ci/build/${{ env.publish_name }}.dmg 2>/dev/null || true
          echo "package-name=${{ env.publish_name }}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ steps.package.outputs.package-name }}
          path: |
            ci/build/*.dmg
            ci/build/*.app
            output/

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ci/build/${{ steps.package.outputs.package-name }}.dmg
          asset_name: ${{ steps.package.outputs.package-name }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
